version: "3.9"

services:
  oidc:
    image: maggch/dingtalk-oidc:latest
    container_name: dingtalk-oidc-dev
    restart: unless-stopped
    environment:
      # Public base URL (adjust if behind reverse proxy / HTTPS)
      ISSUER: "http://localhost:8086"
      # Provide your DingTalk app credentials (required)
      DINGTALK_CLIENT_ID: "change_me_app_key"
      DINGTALK_CLIENT_SECRET: "change_me_app_secret"
      # Optional: Comma-separated list of allowed redirect URLs for security
      # If not set, all redirect URLs will be accepted (less secure)
      # Example: "http://localhost:3000/callback,https://myapp.example.com/auth/callback"
      ALLOWED_REDIRECT_URLS: "http://localhost:3000/callback,http://localhost:8080/callback"
      # Optional: Path to JavaScript file to transform claims before signing the ID token
      # The script should define a transform(claims) function that returns modified claims
      # If not set, claims will be used as-is without transformation
      # Example: "/app/config/transform.js"
      # CLAIMS_TRANSFORM_SCRIPT: "/app/config/transform.js"
      # ADDRESS left default (:8086) inside container
    # volumes:
    #   # Mount your custom transform script
    #   - ./example-transform.js:/app/config/transform.js:ro
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "/app/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # networks:
    #   - oidc_net

# Optional dedicated network (uncomment service networks section above if used)
# networks:
#   oidc_net:
#     driver: bridge
